FROM --platform=linux/amd64 python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .
WORKDIR app/PDF_text_extractor      

ENTRYPOINT ["python", "main.py"]
